/**
 * GO GOA CAR BOOKING - VEHICLE FLEET DATA
 * 
 * This is the CENTRAL database for all cars.
 * If you edit names, prices, images, or specs in this file, they will 
 * AUTOMATICALLY update on all pages: Home, Fleet, Thar, Family, and Luxury sections!
 * 
 * INSTRUCTIONS FOR VS CODE:
 * 1. To change a car's Name: Edit the "name" field.
 * 2. To change a car's Price: Edit the "pricePerDay" field.
 * 3. To change a car's Image: Edit the "imageUrl" field with an Unsplash or any direct image URL.
 * 4. To change Security Deposit: Edit the "securityDeposit" field.
 * 5. To change Transmission (Manual/Automatic): Edit the "transmission" field.
 */

window.CARS = [
  {
    id: 'wagon-r',
    name: 'Maruti Wagon R',
    category: 'Hatchback',
    transmission: 'Manual',
    fuelType: 'Petrol',
    seats: 5,
    luggage: 2,
    pricePerDay: 1000,
    securityDeposit: 2000,
    imageUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=600',
    features: ['Power Steering', 'Air Conditioner', 'Bluetooth Music System', 'USB Charging', 'Excellent Mileage'],
    isPopular: true,
    tagline: 'Hatchback • Smart Comfort',
    engine: '1.2L K-Series DualJet Dual VVT Petrol',
    power: '88.5 BHP @ 6000 RPM',
    clearance: '165 mm standard clearance',
    waterWading: '150 mm',
    suitability: 'Best compact hatch for Goan narrow streets and easy parking.',
    rules: 'No smoking. Return fuel level matching pickup.',
    classType: 'Compact Family Hatchback'
  },
  {
    id: 'swift-manual',
    name: 'Maruti Suzuki Swift',
    category: 'Hatchback',
    transmission: 'Manual',
    fuelType: 'Petrol',
    seats: 5,
    luggage: 2,
    pricePerDay: 1300,
    securityDeposit: 2000,
    imageUrl: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=600',
    features: ['Touchscreen Apple CarPlay', 'Reverse Parking Sensors', 'Air Conditioner', 'Dual Airbags', 'Alloy Wheels'],
    isPopular: true,
    tagline: 'Hatchback • High Mileage',
    engine: '1.2L K-Series DualJet Dual VVT Petrol',
    power: '88.5 BHP @ 6000 RPM',
    clearance: '163 mm - 170 mm standard suspension',
    waterWading: '150 mm',
    suitability: 'Best fuel-economical hatchback for navigating heavy beach corridors of Baga-Calangute or fitting small tight parking layouts.',
    rules: 'Maintain speeds under 70 km/h. Keep clutch riding minimized on extremely steep forest hill sections.',
    classType: 'Budget Compact Family Hatchback'
  },
  {
    id: 'swift-auto',
    name: 'Maruti Suzuki Swift AMT',
    category: 'Hatchback',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 5,
    luggage: 2,
    pricePerDay: 1500,
    securityDeposit: 3000,
    imageUrl: 'https://images.unsplash.com/photo-1525609004556-c46c7d6cf0a3?auto=format&fit=crop&q=80&w=600',
    features: ['Smooth Automatic AMT', 'Keyless Push Start', 'Touchscreen Infotainment', 'Steering Mounted Controls', 'Dual Airbags'],
    isPopular: false,
    tagline: 'Hatchback • Smooth AMT',
    engine: '1.2L K-Series DualJet Dual VVT Petrol',
    power: '88.5 BHP @ 6000 RPM',
    clearance: '163 mm - 170 mm standard suspension',
    waterWading: '150 mm',
    suitability: 'Best fuel-economical hatchback for navigating heavy beach corridors of Baga-Calangute or fitting small tight parking layouts.',
    rules: 'Maintain speeds under 70 km/h. Keep clutch riding minimized on extremely steep forest hill sections.',
    classType: 'Budget Compact Family Hatchback'
  },
  {
    id: 'baleno-auto',
    name: 'Maruti Suzuki Baleno Alpha',
    category: 'Hatchback',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 5,
    luggage: 3,
    pricePerDay: 1700,
    securityDeposit: 3000,
    imageUrl: 'https://images.unsplash.com/photo-1619682855113-dced48f654b0?auto=format&fit=crop&q=80&w=600',
    features: ['Premium Cabin Space', '360 View Camera', 'Head-Up Display (HUD)', 'Automatic Climate Control', 'Push Button Start'],
    isPopular: true,
    tagline: 'Luxury Hatchback • Top tier specs',
    engine: '1.2L K-Series DualJet Dual VVT Petrol',
    power: '88.5 BHP @ 6000 RPM',
    clearance: '163 mm - 170 mm standard suspension',
    waterWading: '150 mm',
    suitability: 'Best fuel-economical hatchback for navigating heavy beach corridors of Baga-Calangute or fitting small tight parking layouts.',
    rules: 'Maintain speeds under 70 km/h. Keep clutch riding minimized on extremely steep forest hill sections.',
    classType: 'Budget Compact Family Hatchback'
  },
  {
    id: 'creta',
    name: 'Hyundai Creta SX',
    category: 'SUV',
    transmission: 'Manual',
    fuelType: 'Diesel',
    seats: 5,
    luggage: 4,
    pricePerDay: 2300,
    securityDeposit: 3000,
    imageUrl: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&q=80&w=600',
    features: ['Panoramic Sunroof', 'Digital Instrument Cluster', 'Powerful CRDi Turbo Engine', 'Cooling Glove Box', 'LED Headlamps'],
    isPopular: true,
    tagline: 'SUV • Feature Rich',
    engine: '1.5L CRDi Turbo Diesel Engine',
    power: '115 PS @ 4000 RPM',
    clearance: '190 mm segment-defining ground height',
    waterWading: '250 mm',
    suitability: 'Elegant premium high-rider for highway stability, long road trips across state borders, and exploring winding roads of Goan Ghats.',
    rules: 'Always watch for high curb lines during manual reverse parking. Use the provided high-beam controls mindfully under city flyovers.',
    classType: 'Full Comfort Mid-Size SUV'
  },
  {
    id: 'thar-4x4-manual',
    name: 'Mahindra Thar 4x4 MT',
    category: 'Thar',
    transmission: 'Manual',
    fuelType: 'Diesel',
    seats: 4,
    luggage: 2,
    pricePerDay: 2800,
    securityDeposit: 4000,
    imageUrl: 'https://images.unsplash.com/photo-1616422285623-13ff0162193c?auto=format&fit=crop&q=80&w=600',
    features: ['Real 4x4 Low-Range Transfer Case', 'Rugged Hard-Top Roof', 'Excellent Water Wading', 'Heavy-Duty Alloy Wheels', 'Adventure GPS Tracker'],
    isPopular: true,
    tagline: 'True 4x4 Offroader • Manual',
    engine: '2.2L mHawk Turbo Diesel',
    power: '130 BHP @ 3750 RPM',
    clearance: '226 mm (Class-leading height)',
    waterWading: '650 mm (Perfect for monsoons)',
    suitability: 'Perfect for exploring Goa\'s rustic interior forest roads, historic fort drives, and steep cliff routes of Cola & Cabo de Rama.',
    rules: 'Absolute zero drift over sandy beach lines (heavy local authority fines). Ensure the vehicle stays locked in 2H mode on dry tarmac.',
    classType: 'Adventure Offroad 4x4 Jeep'
  },
  {
    id: 'thar-4x4-auto',
    name: 'Mahindra Thar 4x4 Automatic',
    category: 'Thar',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 4,
    luggage: 2,
    pricePerDay: 3200,
    securityDeposit: 4000,
    imageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=600',
    features: ['Effortless Torque-Converter AT', 'Convertible Soft-Top (Open Air)', 'Cruising Power Grid', 'Touch Infotainment System', 'Off-road Driving Modes'],
    isPopular: true,
    tagline: 'True 4x4 Offroader • Automatic',
    engine: '2.0L mStallion TGDi Petrol',
    power: '150 BHP @ 5000 RPM',
    clearance: '226 mm ground clearance',
    waterWading: '650 mm',
    suitability: 'Perfect for sunset drives in open air, beach-side cruising, and effortless off-road exploration.',
    rules: 'Maintain low speed when top is open. Secure soft-top locks properly before speeding up.',
    classType: 'Adventure Offroad 4x4 convertible'
  },
  {
    id: 'ertiga',
    name: 'Maruti Suzuki Ertiga (7-Seater)',
    category: 'SUV',
    transmission: 'Manual',
    fuelType: 'Petrol',
    seats: 7,
    luggage: 4,
    pricePerDay: 2200,
    securityDeposit: 3000,
    imageUrl: 'https://images.unsplash.com/photo-1626847037657-fd3622613ce3?auto=format&fit=crop&q=80&w=600',
    features: ['Spacious 3-Row Seating', 'Roof Mounted Rear AC Vents', 'Convertible Cargo Space', 'Excellent for Groups & Families', 'Elegant Projector Lamps'],
    isPopular: true,
    tagline: '7 Seats • Budget Smart Family',
    engine: '1.5L SmartHybrid K15C Petrol Engine',
    power: '103 PS @ 6000 RPM',
    clearance: '180 mm multi-passenger ground height',
    waterWading: '200 mm',
    suitability: 'The gold standard for mid-budget travel packages, facilitating extended family reunions or group outings to Dudhsagar waterfalls.',
    rules: 'Always keep the last row flat if carrying heavy bulk luggage. Drive at conservative speeds when fully loaded with 7 adults.',
    classType: '7-Seater Family Tourer MPV'
  },
  {
    id: 'innova-crysta',
    name: 'Toyota Innova Crysta ZX',
    category: 'Luxury',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    seats: 7,
    luggage: 5,
    pricePerDay: 4500,
    securityDeposit: 5000,
    imageUrl: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=600',
    features: ['Captain Seats Luxury Pack', 'Whisper-Quiet Cabin', 'Premium Leather Interiors', 'Dual SRS Airbags with ABS', 'Bulletproof Toyota Reliability'],
    isPopular: true,
    tagline: '7 Seats • Premium Captain Row',
    engine: '2.4L GD-Series Turbocharged Common Rail Diesel',
    power: '150 PS @ 3400 RPM',
    clearance: '178 mm luxury passenger-comfort platform',
    waterWading: '300 mm',
    suitability: 'The absolute pinnacle of luxury road cruising. Perfectly tailored for business conferences, high-profile events, and families demanding first-class lounge comfort.',
    rules: 'Treated with premium high-grade upholstery, kindly avoid spillable oil-based snacks inside. Strictly adhere to regional speed limit cameras.',
    classType: 'First-Class Premium Executive MPV'
  },
  {
    id: 'dzire-manual',
    name: 'Maruti Suzuki Dzire VXI',
    category: 'Hatchback',
    transmission: 'Manual',
    fuelType: 'Petrol',
    seats: 5,
    luggage: 3,
    pricePerDay: 1400,
    securityDeposit: 2000,
    imageUrl: 'https://images.unsplash.com/photo-1532581291347-9c39cf10a73c?auto=format&fit=crop&q=80&w=600',
    features: ['Comfortable Sedan Boot', 'Very High Fuel Economy', 'SmartPlay Infotainment', 'Rear AC Vents', 'Smooth Suspension Click'],
    isPopular: false,
    tagline: 'Compact Sedan • Fuel Efficient',
    engine: '1.2L DualJet Petrol',
    power: '90 BHP',
    clearance: '163 mm ground clearance',
    waterWading: '150 mm',
    suitability: 'Perfect for couples and small families requiring a full-size luggage boot for airport transfers.',
    rules: 'Drive within Goa speed limits. Lock the boot securely before driving.',
    classType: 'Compact Family Sedan'
  },
  {
    id: 'jimny-manual',
    name: 'Maruti Suzuki Jimny 4x4 MT',
    category: 'Thar',
    transmission: 'Manual',
    fuelType: 'Petrol',
    seats: 4,
    luggage: 2,
    pricePerDay: 2300,
    securityDeposit: 3000,
    imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=600',
    features: ['Compact 4x4 Offroader', 'ALLGRIP PRO Engine Tech', 'Retro Nostalgic Looks', 'Solid Off-Road Axles', 'Spacious Cabin Utility'],
    isPopular: true,
    tagline: 'Compact 4x4 Offroader',
    engine: '1.5L K15B Petrol Engine',
    power: '104 BHP',
    clearance: '210 mm off-road ground clearance',
    waterWading: '400 mm',
    suitability: 'Ideal for travelers looking for retro 4x4 aesthetics coupled with easy maneuvering on narrow streets.',
    rules: 'Utilize 4H/4L modes only on loose sand, gravel, or muddy trails. Avoid asphalt 4x4 binding.',
    classType: 'Retro Utility 4x4 SUV'
  },
  {
    id: 'thar-rwd-auto',
    name: 'Mahindra Thar RWD Automatic',
    category: 'Thar',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 4,
    luggage: 2,
    pricePerDay: 2900,
    securityDeposit: 4000,
    imageUrl: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&q=80&w=600',
    features: ['Responsive Turbo Petrol AT', 'RWD High Ground Clearance', 'Sporty Black Alloy Rims', 'Thumping Music System', 'Perfect For Sunset Cruising'],
    isPopular: true,
    tagline: 'Sporty SUV • Wind Cruiser',
    engine: '1.5L Turbo Diesel / 2.0L TGDi Petrol',
    power: '150 BHP mStallion power Output',
    clearance: '226 mm standard ground elevation',
    waterWading: '450 mm',
    suitability: 'Cruising around coastal state highways, catching stunning evening sunset views with high command styling.',
    rules: 'RWD configuration. Strictly do not engage in deep marshy off-road valleys requiring low-gearing.',
    classType: 'High-riding Beach Runner SUV'
  },
  {
    id: 'scorpio-classic',
    name: 'Mahindra Scorpio Classic S11',
    category: 'SUV',
    transmission: 'Manual',
    fuelType: 'Diesel',
    seats: 7,
    luggage: 4,
    pricePerDay: 2600,
    securityDeposit: 3000,
    imageUrl: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=600',
    features: ['Legendary Muscular Stance', 'mHawk Turbo Diesel Power', 'Premium 9-inch Touchscreen', 'Captain Seats Arrangement', 'Very Commanding Views'],
    isPopular: false,
    tagline: 'Muscular SUV • Powerful Drive',
    engine: '2.2L mHawk Common Rail Diesel',
    power: '130 BHP',
    clearance: '180 mm raw ground clearance',
    waterWading: '350 mm',
    suitability: 'Muscular road presence for larger groups requiring powerful diesel performance on long highway routes.',
    rules: 'Avoid aggressive over-speeding on bridge sections. Maintain proper parking alignment.',
    classType: 'Semi-Luxury Heavy Road SUV'
  },
  {
    id: 'i20-auto',
    name: 'Hyundai i20 Asta IVT',
    category: 'Hatchback',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 5,
    luggage: 2,
    pricePerDay: 1600,
    securityDeposit: 2000,
    imageUrl: 'https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&q=80&w=600',
    features: ['Premium Hatchback Comfort', 'Super Smooth IVT Automatic', 'Electric Sunroof Deck', 'Bose Premium Speakers', 'Ambient Cabin Lighting'],
    isPopular: false,
    tagline: 'Premium Cabin • IVT Smoothness',
    engine: '1.2L Kappa Petrol IVT',
    power: '83 BHP',
    clearance: '170 mm standard city clearance',
    waterWading: '150 mm',
    suitability: 'Superbly quiet city hatchback suited for late night gourmet dining road commutes or family trips.',
    rules: 'Operate sunroof slider gently. Lock windows when running air conditioner.',
    classType: 'Smart Luxury Urban Hatch'
  },
  {
    id: 'seltos-auto',
    name: 'Kia Seltos HTX CVT',
    category: 'SUV',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 5,
    luggage: 3,
    pricePerDay: 2400,
    securityDeposit: 3000,
    imageUrl: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&q=80&w=600',
    features: ['Panoramic Sunroof Glass', 'Dual-Screen High-Tech Dashboard', 'LED Crown Jewel Headlamps', 'Smart Pure Air Purifier', 'Extremely Smooth Driving'],
    isPopular: true,
    tagline: 'Tech SUV • Panoramic Vista',
    engine: '1.5L Smartstream MPi Petrol',
    power: '115 PS output capability',
    clearance: '190 mm robust ground stance',
    waterWading: '220 mm',
    suitability: 'Lovers of high-technology features, smart electronic aids, and beautiful dual-dashboard views.',
    rules: 'Do not stand through the open panoramic sunroof while the vehicle is in motion (strict fine).',
    classType: 'Smart Feature-packed Digital SUV'
  },
  {
    id: 'audi-q3',
    name: 'Audi Q3 Premium Automatic',
    category: 'Luxury',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 5,
    luggage: 4,
    pricePerDay: 6550,
    securityDeposit: 7000,
    imageUrl: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&q=80&w=600',
    features: ['Quattro All-Wheel Drive', 'Panoramic Dual Sunroof', 'Virtual Cockpit Display', 'Leather Sports Seats', 'Elite Luxury Status Symbol'],
    isPopular: true,
    tagline: 'German Luxury • Premium AWD',
    engine: '2.0L TFSI Turbocharged Petrol',
    power: '190 BHP high output',
    clearance: '200 mm high premium clearance',
    waterWading: '500 mm',
    suitability: 'Ultra premium sports crossover choice for executive clients, VIP leisure vacations, and luxury coastal hotel stays.',
    rules: 'Use 95+ Octane premium fuel if self-refueling. Maintain clean elite condition of leather seats.',
    classType: 'German Luxury Sporty Crossover'
  },
  {
    id: 'fortuner-suv',
    name: 'Toyota Fortuner Sigma 4x4',
    category: 'Luxury',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    seats: 7,
    luggage: 5,
    pricePerDay: 5500,
    securityDeposit: 6000,
    imageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=600',
    features: ['Brutal 4x4 Off-Road Power', 'Commanding Road Presence', 'Ventilated Front Seats', 'Premium JBL Audio System', 'Legendary Toyota Reliability'],
    isPopular: true,
    tagline: 'Colossal Offroad King',
    engine: '2.8L Powerful GD-Turbo Diesel',
    power: '204 BHP massive muscle',
    clearance: '220 mm off-road platform',
    waterWading: '700 mm',
    suitability: 'VIP heavy-duty tours, premium family road presence, and dominant driving feel anywhere in Western India.',
    rules: 'Adhere to defensive speed metrics. Always check tail spacing when reversing this heavy vehicle.',
    classType: 'Dominant Luxury Muscle SUV'
  },
  {
    id: 'nexon-ev',
    name: 'Tata Nexon EV Max',
    category: 'SUV',
    transmission: 'Automatic',
    fuelType: 'Electric',
    seats: 5,
    luggage: 3,
    pricePerDay: 2000,
    securityDeposit: 3000,
    imageUrl: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&q=80&w=600',
    features: ['100% Eco-Friendly Drive', 'Sunroof & Ventilated Seats', 'Quiet & Instant Torque', 'Wireless Charger Pad', 'Very Low Travel Energy Cost'],
    isPopular: false,
    tagline: 'Zero Emissions • Silent Cruise',
    engine: 'High Power Permanent Magnet AC Motor',
    power: '143 PS electric power output',
    clearance: '205 mm high ev ground height',
    waterWading: '300 mm',
    suitability: 'Eco-conscious explorers demanding low noise floor, quiet cabin, and completely free electricity charge utility across Goa.',
    rules: 'Charge battery using official fast charger ports. Return vehicle with at least 15% range left.',
    classType: 'Eco-Smart Clean Energy EV'
  },
  {
    id: 'bmw-3',
    name: 'BMW 3 Series M Sport',
    category: 'Luxury',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 5,
    luggage: 3,
    pricePerDay: 8500,
    securityDeposit: 10000,
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=600',
    features: ['M Sport Aerodynamic Kit', 'Harman Kardon Surround Sound', 'Live Virtual Live Cockpit', 'Dynamic Driving Control Modes', 'Ultra Premium Luxury Drive'],
    isPopular: true,
    tagline: 'High Performance Luxury Sedan',
    engine: '2.0L TwinPower Turbo inline 4-cylinder Petrol',
    power: '258 BHP dynamic power output',
    clearance: '136 mm premium low-slung sedan setup',
    waterWading: '120 mm',
    suitability: 'Experiencing ultimate performance luxury, precision sports handling, and first class styling on your Goa holiday.',
    rules: 'Drive defensively over speed breakers. Absolutely do not attempt to enter marshy sand spaces.',
    classType: 'German high-performance premium saloon'
  }
];

// Compatibility Layers for older page setups
window.CARS_DATA = {};
window.CARS_DATABASE = {};

window.CARS.forEach(car => {
  // Map legacy property names for backwards compatibility
  car.image = car.imageUrl;
  car.rent = car.pricePerDay;
  car.deposit = car.securityDeposit;
  car.fuel = car.fuelType;
  car.bags = typeof car.luggage === 'number' ? `${car.luggage} Bags` : car.luggage;
  car.wading = car.waterWading;
  
  window.CARS_DATA[car.id] = car;
  window.CARS_DATABASE[car.id] = car;
});
